// dummyMeetings.ts
import type { MeetingData } from "@/domain/entities/calendar/MeetingData";
import { TMeetingColor } from "@/domain/types/calendar/types";
  const now = new Date();
  const startRange = new Date(now);
  startRange.setDate(now.getDate() - 30);
  const endRange = new Date(now);
  endRange.setDate(now.getDate() + 30);

export const COLORS = ["blue", "green", "red", "orange", "purple", "yellow"];

export const dummyMeetings: MeetingData[] = [
  {
    meeting_id: '1',
    title: 'European Project Kickoff 1',
    meeting_url: 'https://zoom.us/j/123456789',
   meeting_start_datetime: '2025-05-21T14:30:00.000Z',
    meeting_end_datetime: '2025-05-21T15:30:00.000Z',
    location: 'Zoom',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Initial project kickoff meeting with all stakeholders.',
    tags: ['kickoff', 'project', 'team'],
  },
  {
    meeting_id: '2',
    title: 'Germany New Legislation Discussion 1',
    meeting_url: 'https://meet.google.com/abc-defg-hij',
    meeting_start_datetime: '2025-05-19T14:30:00.000Z',
    meeting_end_datetime: '2025-05-21T15:30:00.000Z',
    location: 'Google Meet',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Review design prototypes and get feedback.',
    tags: ['design', 'review'],
  }, 
  {
    meeting_id: '1',
    title: 'European Project Kickoff 2',
    meeting_url: 'https://zoom.us/j/123456789',
    meeting_start_datetime: '2025-05-26T14:30:00.000Z',
    meeting_end_datetime: '2025-05-26T15:30:00.000Z',
    location: 'Zoom',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Initial project kickoff meeting with all stakeholders.',
    tags: ['kickoff', 'project', 'team'],
  },
  {
    meeting_id: '2',
    title: 'Germany New Legislation Discussion 2',
    meeting_url: 'https://meet.google.com/abc-defg-hij',
    meeting_start_datetime: '2025-05-12T16:00:00.000Z',
    meeting_end_datetime: '2025-05-16T17:00:00.000Z',
    location: 'Google Meet',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Discussion on the upcoming legislation and implications.',
    tags: ['legislation', 'germany', 'policy'],
  },
  {
    meeting_id: '3',
    title: 'Marketing Strategy Sync 3',
    meeting_url: 'https://zoom.us/j/987654321',
    meeting_start_datetime: '2025-04-28T10:00:00.000Z',
    meeting_end_datetime: '2025-05-02T11:00:00.000Z',
    location: 'Zoom',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Align marketing plans for the product launch.',
    tags: ['marketing', 'strategy', 'launch'],
  },
  {
    meeting_id: '4',
    title: 'Tech Team Sprint Planning 3',
    meeting_url: 'https://teams.microsoft.com/l/meetup-join/123',
    meeting_start_datetime: '2025-05-26T09:00:00.000Z',
    meeting_end_datetime: '2025-05-30T10:30:00.000Z',
    location: 'Microsoft Teams',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Plan sprints and assign tasks for the next development cycle.',
    tags: ['sprint', 'planning', 'tech'],
  },
  {
    meeting_id: '5',
    title: 'Investor Update Call 3',
    meeting_url: 'https://meet.google.com/xyz-abc-def',
    meeting_start_datetime: '2025-05-29T13:00:00.000Z',
    meeting_end_datetime: '2025-05-29T14:00:00.000Z',
    location: 'Google Meet',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Provide financial updates and progress to investors.',
    tags: ['investor', 'finance', 'update'],
  },
  {
    meeting_id: '6',
    title: 'Design Review Session 4',
    meeting_url: 'https://zoom.us/j/555555555',
    meeting_start_datetime: '2025-05-30T15:00:00.000Z',
    meeting_end_datetime: '2025-05-30T16:30:00.000Z',
    location: 'Zoom',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Review design prototypes and gather stakeholder feedback.',
    tags: ['design', 'review', 'feedback'],
  },
  {
    meeting_id: '7',
    title: 'Product Roadmap Workshop 4',
    meeting_url: 'https://teams.microsoft.com/l/meetup-join/456',
    meeting_start_datetime: '2025-05-31T11:00:00.000Z',
    meeting_end_datetime: '2025-05-31T12:30:00.000Z',
    location: 'Microsoft Teams',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Collaborative session to shape the next quarter\'s roadmap.',
    tags: ['roadmap', 'product', 'workshop'],
  },
  {
    meeting_id: '8',
    title: 'AI Ethics Committee 4',
    meeting_url: 'https://zoom.us/j/333333333',
    meeting_start_datetime: '2025-05-19T14:00:00.000Z',
    meeting_end_datetime: '2025-05-19T15:30:00.000Z',
    location: 'Zoom',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Discuss ethical implications of the latest AI features.',
    tags: ['AI', 'ethics', 'committee'],
  },
  {
    meeting_id: '9',
    title: 'Customer Success Check-In 4',
    meeting_url: 'https://meet.google.com/def-ghi-jkl',
    meeting_start_datetime: '2025-05-20T09:30:00.000Z',
    meeting_end_datetime: '2025-05-20T10:30:00.000Z',
    location: 'Google Meet',
    color: COLORS[Math.floor(Math.random() * COLORS.length)],
    description: 'Check in with key customers and address concerns.',
    tags: ['customer', 'success', 'check-in'],
  }
];