const MOCK_COUNTRY_MEETING_MAP = new Map([
  ['Austria', { totalCount: 7, meetings: [], meetingTypeMap: {} }],
  ['Belgium', { totalCount: 2, meetings: [], meetingTypeMap: {} }],
  ['Bulgaria', { totalCount: 6, meetings: [], meetingTypeMap: {} }],
  ['Croatia', { totalCount: 4, meetings: [], meetingTypeMap: {} }],
  ['Cyprus', { totalCount: 3, meetings: [], meetingTypeMap: {} }],
  ['Czech Republic', { totalCount: 8, meetings: [], meetingTypeMap: {} }],
  ['Denmark', { totalCount: 2, meetings: [], meetingTypeMap: {} }],
  ['Estonia', { totalCount: 5, meetings: [], meetingTypeMap: {} }],
  ['Finland', { totalCount: 6, meetings: [], meetingTypeMap: {} }],
  ['France', { totalCount: 9, meetings: [], meetingTypeMap: {} }],
  ['Germany', { totalCount: 5, meetings: [], meetingTypeMap: {} }],
  ['Greece', { totalCount: 4, meetings: [], meetingTypeMap: {} }],
  ['Hungary', { totalCount: 3, meetings: [], meetingTypeMap: {} }],
  ['Ireland', { totalCount: 2, meetings: [], meetingTypeMap: {} }],
  ['Italy', { totalCount: 3, meetings: [], meetingTypeMap: {} }],
  ['Latvia', { totalCount: 6, meetings: [], meetingTypeMap: {} }],
  ['Lithuania', { totalCount: 4, meetings: [], meetingTypeMap: {} }],
  ['Luxembourg', { totalCount: 1, meetings: [], meetingTypeMap: {} }],
  ['Malta', { totalCount: 3, meetings: [], meetingTypeMap: {} }],
  ['Netherlands', { totalCount: 8, meetings: [], meetingTypeMap: {} }],
  ['Poland', { totalCount: 6, meetings: [], meetingTypeMap: {} }],
  ['Portugal', { totalCount: 4, meetings: [], meetingTypeMap: {} }],
  ['Romania', { totalCount: 7, meetings: [], meetingTypeMap: {} }],
  ['Slovakia', { totalCount: 5, meetings: [], meetingTypeMap: {} }],
  ['Slovenia', { totalCount: 2, meetings: [], meetingTypeMap: {} }],
  ['Spain', { totalCount: 9, meetings: [], meetingTypeMap: {} }],
  ['Sweden', { totalCount: 3, meetings: [], meetingTypeMap: {} }],
]);

export default MOCK_COUNTRY_MEETING_MAP;
